name: Cargo Build & Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    env:
      PERSEUS_VERSION: 0.4.0
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Checkout respository
        uses: actions/checkout@v4

      - name: Cache Cargo and Rustup
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
          # The cache should be OS-specific
          key: ${{ runner.os }}-website-cargo-bins-$PERSEUS_VERSION

      - name: Setup Rust
        if: steps.cache.outputs.cache-hit != 'true'
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      # Only install the binaries if the cache doesn't have them
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install perseus-cli --version $PERSEUS_VERSION

      - name: Cache local build
        uses: actions/cache@v4
        with:
          path: |
            target/
            dist/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Check using Perseus
        run: perseus check
